from django.urls import path

from dashboard.views import (
    AcademicOverviewView,
    AdminRootRedirectView,
    AgendaCardCreateView,
    AgendaCardDeleteView,
    AgendaCardUpdateView,
    AspirationDeleteView,
    AspirationDetailView,
    AspirationFeatureToggleView,
    AspirationListView,
    CabinetCalendarCreateView,
    CabinetCalendarDeleteView,
    CabinetCalendarUpdateView,
    CareerSettingsView,
    CompetencyPageView,
    CompetencyWinnerSlideCreateView,
    CompetencyWinnerSlideDeleteView,
    CompetencyWinnerSlideUpdateView,
    CountdownEventCreateView,
    CountdownEventDeleteView,
    CountdownEventUpdateView,
    DashboardHomeView,
    DashboardLoginView,
    DashboardLogoutView,
    DashboardProfileView,
    QuickDownloadCreateView,
    QuickDownloadDeleteView,
    QuickDownloadUpdateView,
    RepositoryMaterialCreateView,
    RepositoryMaterialDeleteView,
    RepositoryMaterialSlotUpdateView,
    RepositoryMaterialUpdateView,
    TicketTrackingAdminView,
    AboutSettingsView,
)

urlpatterns = [
    path("", AdminRootRedirectView.as_view(), name="root"),
    path("login/", DashboardLoginView.as_view(), name="login"),
    path("logout/", DashboardLogoutView.as_view(), name="logout"),
    path("dashboard/", DashboardHomeView.as_view(), name="home"),
    path("profile/", DashboardProfileView.as_view(), name="profile"),
    path("tentang-kami/", AboutSettingsView.as_view(), name="about"),
    path("tentang-kami/kalender/tambah/", CabinetCalendarCreateView.as_view(), name="cabinet-calendar-create"),
    path("tentang-kami/kalender/<uuid:pk>/edit/", CabinetCalendarUpdateView.as_view(), name="cabinet-calendar-update"),
    path(
        "tentang-kami/kalender/<uuid:pk>/hapus/",
        CabinetCalendarDeleteView.as_view(),
        name="cabinet-calendar-delete",
    ),
    path("akademik/", AcademicOverviewView.as_view(), name="academic"),
    path("akademik/quick-downloads/tambah/", QuickDownloadCreateView.as_view(), name="quick-download-create"),
    path("akademik/quick-downloads/<uuid:pk>/edit/", QuickDownloadUpdateView.as_view(), name="quick-download-update"),
    path(
        "akademik/quick-downloads/<uuid:pk>/hapus/",
        QuickDownloadDeleteView.as_view(),
        name="quick-download-delete",
    ),
    path("akademik/repository/tambah/", RepositoryMaterialCreateView.as_view(), name="repository-create"),
    path(
        "akademik/repository/<str:section>/slot/<int:slot>/edit/",
        RepositoryMaterialSlotUpdateView.as_view(),
        name="repository-slot-update",
    ),
    path("akademik/repository/<uuid:pk>/edit/", RepositoryMaterialUpdateView.as_view(), name="repository-update"),
    path("akademik/repository/<uuid:pk>/hapus/", RepositoryMaterialDeleteView.as_view(), name="repository-delete"),
    path("akademik/countdown/tambah/", CountdownEventCreateView.as_view(), name="countdown-create"),
    path("akademik/countdown/<uuid:pk>/edit/", CountdownEventUpdateView.as_view(), name="countdown-update"),
    path("akademik/countdown/<uuid:pk>/hapus/", CountdownEventDeleteView.as_view(), name="countdown-delete"),
    path("kompetensi-karir/kompetensi/", CompetencyPageView.as_view(), name="competency"),
    path(
        "kompetensi-karir/kompetensi/winner-slides/tambah/",
        CompetencyWinnerSlideCreateView.as_view(),
        name="winner-slide-create",
    ),
    path(
        "kompetensi-karir/kompetensi/winner-slides/<uuid:pk>/edit/",
        CompetencyWinnerSlideUpdateView.as_view(),
        name="winner-slide-update",
    ),
    path(
        "kompetensi-karir/kompetensi/winner-slides/<uuid:pk>/hapus/",
        CompetencyWinnerSlideDeleteView.as_view(),
        name="winner-slide-delete",
    ),
    path("kompetensi-karir/kompetensi/tambah/", AgendaCardCreateView.as_view(), name="agenda-card-create"),
    path("kompetensi-karir/kompetensi/<uuid:pk>/edit/", AgendaCardUpdateView.as_view(), name="agenda-card-update"),
    path("kompetensi-karir/kompetensi/<uuid:pk>/hapus/", AgendaCardDeleteView.as_view(), name="agenda-card-delete"),
    path("kompetensi-karir/karir/", CareerSettingsView.as_view(), name="career"),
    path("advokasi/aspirasi/", AspirationListView.as_view(), name="aspiration-list"),
    path("advokasi/aspirasi/<uuid:pk>/", AspirationDetailView.as_view(), name="aspiration-detail"),
    path("advokasi/aspirasi/<uuid:pk>/hapus/", AspirationDeleteView.as_view(), name="aspiration-delete"),
    path(
        "advokasi/aspirasi/<uuid:pk>/set-featured/",
        AspirationFeatureToggleView.as_view(),
        {"feature_action": "set"},
        name="aspiration-set-featured",
    ),
    path(
        "advokasi/aspirasi/<uuid:pk>/unset-featured/",
        AspirationFeatureToggleView.as_view(),
        {"feature_action": "unset"},
        name="aspiration-unset-featured",
    ),
    path("advokasi/lacak-tiket/", TicketTrackingAdminView.as_view(), name="ticket-tracking"),
]
