# Generated by Django 6.0.3 on 2026-05-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_career_dashboard_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dashboard_access_scope',
            field=models.CharField(choices=[('full', 'Superadmin'), ('academic', 'Akademik'), ('competency', 'Kompetensi'), ('career', 'Karir'), ('advocacy', 'Advokasi')], default='full', max_length=20),
        ),
    ]
