# Generated by Django 6.0.3 on 2026-03-15 04:33

import core.models
import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='competencyprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competencyprogram',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competencyprogram',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.UploadToPath('competency/programs'), validators=[core.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='competencyprogram',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
