# Generated by Django 6.0.3 on 2026-03-15 05:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0002_competencyprogram_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('urgency_tag', models.CharField(max_length=100)),
                ('recommendation_tag', models.CharField(max_length=100)),
                ('category_tag', models.CharField(max_length=100)),
                ('scope_tag', models.CharField(max_length=100)),
                ('pricing_tag', models.CharField(max_length=100)),
                ('deadline_date', models.DateField()),
                ('registration_link', models.URLField()),
                ('google_calendar_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'deadline_date', 'title'],
            },
        ),
    ]
