# Generated by Django 6.0.3 on 2026-03-18 11:30

import django.core.validators
from django.db import migrations, models


def populate_agenda_boolean_tags(apps, schema_editor):
    AgendaCard = apps.get_model("competency", "AgendaCard")
    falsy_values = {"", "0", "false", "no", "tidak", "none", "null"}

    for agenda_card in AgendaCard.objects.all().iterator():
        urgency_value = str(getattr(agenda_card, "urgency_tag_legacy", "") or "").strip().lower()
        recommendation_value = str(getattr(agenda_card, "recommendation_tag_legacy", "") or "").strip().lower()

        AgendaCard.objects.filter(pk=agenda_card.pk).update(
            urgency_tag=urgency_value not in falsy_values,
            recommendation_tag=recommendation_value not in falsy_values,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("competency", "0003_agendacard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendacard",
            old_name="urgency_tag",
            new_name="urgency_tag_legacy",
        ),
        migrations.RenameField(
            model_name="agendacard",
            old_name="recommendation_tag",
            new_name="recommendation_tag_legacy",
        ),
        migrations.AddField(
            model_name="agendacard",
            name="urgency_tag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agendacard",
            name="recommendation_tag",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(populate_agenda_boolean_tags, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="agendacard",
            name="short_description",
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name="agendacard",
            name="category_tag",
            field=models.CharField(
                choices=[("workshop", "Workshop"), ("lomba", "Lomba")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agendacard",
            name="scope_tag",
            field=models.CharField(
                choices=[("nasional", "Nasional"), ("internasional", "Internasional")],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="agendacard",
            name="pricing_tag",
            field=models.CharField(
                choices=[("berbayar", "Berbayar"), ("tidak berbayar", "Tidak Berbayar")],
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="agendacard",
            name="urgency_tag_legacy",
        ),
        migrations.RemoveField(
            model_name="agendacard",
            name="recommendation_tag_legacy",
        ),
        migrations.RemoveField(
            model_name="agendacard",
            name="sort_order",
        ),
        migrations.AlterModelOptions(
            name="agendacard",
            options={"ordering": ["-created_at", "-updated_at", "deadline_date", "title"]},
        ),
    ]
