# Generated by Django 6.0.3 on 2026-03-23 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0004_update_agendacard_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendacard',
            name='short_description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(300)]),
        ),
    ]
