# Generated by Django 6.0.3 on 2026-04-05 13:34

import core.models
import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_winner_slide_slots(apps, schema_editor):
    CompetencyWinnerSlide = apps.get_model("competency", "CompetencyWinnerSlide")
    for slot in range(1, 6):
        CompetencyWinnerSlide.objects.get_or_create(
            display_order=slot,
            defaults={"alt_text": f"Winner slide slot {slot}"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0005_alter_agendacard_short_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyWinnerSlide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.UploadToPath('competency/winner-slides'), validators=[core.validators.validate_file_size, core.validators.validate_image_extension])),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(choices=[(1, 'Slot 1'), (2, 'Slot 2'), (3, 'Slot 3'), (4, 'Slot 4'), (5, 'Slot 5')], unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', '-updated_at'],
            },
        ),
        migrations.RunPython(create_default_winner_slide_slots, migrations.RunPython.noop),
    ]
