# Generated by Django 6.0.3 on 2026-04-05 21:50

from django.db import migrations


def rebuild_winner_slide_slots(apps, schema_editor):
    CompetencyWinnerSlide = apps.get_model("competency", "CompetencyWinnerSlide")
    alias = schema_editor.connection.alias
    table_name = CompetencyWinnerSlide._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        table_names = schema_editor.connection.introspection.table_names(cursor)

    if table_name not in table_names:
        return

    valid_slots = [1, 2, 3, 4, 5]

    (
        CompetencyWinnerSlide.objects.using(alias)
        .exclude(display_order__in=valid_slots)
        .delete()
    )

    for slot_number in valid_slots:
        existing = list(
            CompetencyWinnerSlide.objects.using(alias)
            .filter(display_order=slot_number)
            .order_by("created_at", "pk")
        )
        slide = existing[0] if existing else None

        if len(existing) > 1:
            CompetencyWinnerSlide.objects.using(alias).filter(
                pk__in=[item.pk for item in existing[1:]]
            ).delete()

        if slide is None:
            CompetencyWinnerSlide.objects.using(alias).create(
                display_order=slot_number,
                alt_text=f"Winner slide slot {slot_number}",
            )
            continue

        if not slide.alt_text:
            slide.alt_text = f"Winner slide slot {slot_number}"
            slide.save()


class Migration(migrations.Migration):

    dependencies = [
        ("competency", "0006_competencywinnerslide"),
    ]

    operations = [
        migrations.RunPython(rebuild_winner_slide_slots, migrations.RunPython.noop),
    ]
