# Generated by Django 6.0.3 on 2026-04-28 15:12

from django.db import migrations, models


DEFAULT_LOMBA_CARI_TIM_LINK = "https://chat.whatsapp.com/B5zlTriCgv4GOpYxjBiNR7"


def fill_team_finding_link_for_existing_lomba(apps, schema_editor):
    AgendaCard = apps.get_model("competency", "AgendaCard")
    alias = schema_editor.connection.alias

    AgendaCard.objects.using(alias).filter(
        category_tag="lomba",
        team_finding_link="",
    ).update(team_finding_link=DEFAULT_LOMBA_CARI_TIM_LINK)


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0007_rebuild_winner_slide_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacard',
            name='team_finding_link',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(fill_team_finding_link_for_existing_lomba, migrations.RunPython.noop),
    ]
