# Generated by Django 6.0.3 on 2026-05-11 14:57

import competency.models
import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competency', '0008_agendacard_team_finding_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendacard',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.UploadToPath('competency/agenda-cards'), validators=[competency.models.validate_agenda_header_image]),
        ),
    ]
