# Generated by Django 6.0.3 on 2026-05-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_academicdigitalresourceconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorymaterial',
            name='google_drive_link',
            field=models.URLField(verbose_name='Link'),
        ),
    ]
