# Generated by Django 6.0.3 on 2026-03-15 05:10

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirations', '0002_aspiration_created_by_aspiration_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirationSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('npm', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.TextField()),
                ('evidence_attachment', models.FileField(blank=True, null=True, upload_to='aspirations/evidence/', validators=[core.validators.validate_file_size, core.validators.validate_image_or_pdf_extension])),
                ('ticket_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('anonymous', 'Anonymous')], default='anonymous', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('upvote_count', models.PositiveIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Aspiration',
        ),
    ]
