# Generated by Django 6.0.3 on 2026-03-15 05:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirations', '0003_aspirationsubmission_delete_aspiration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AspirationActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('updated', 'Updated'), ('featured', 'Featured'), ('unfeatured', 'Unfeatured')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('status_snapshot', models.CharField(choices=[('submitted', 'Submitted'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], max_length=20)),
                ('visibility_snapshot', models.CharField(choices=[('public', 'Public'), ('anonymous', 'Anonymous')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('aspiration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='aspirations.aspirationsubmission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
