# Generated by Django 6.0.3 on 2026-05-17 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEventCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_key', models.CharField(choices=[('home.hero.access_academic', 'Home hero access academic'), ('home.hero.info_competition', 'Home hero info competition'), ('home.about.access_academic', 'Home about access academic'), ('home.about.info_competition', 'Home about info competition'), ('home.features.academic.access_now', 'Home features academic access now'), ('home.features.competency.explore', 'Home features competency explore'), ('home.features.career.view_resource', 'Home features career view resource'), ('home.features.advocacy.submit_aspiration', 'Home features advocacy submit aspiration'), ('home.competency.view_all', 'Home competency view all'), ('home.competency.register', 'Home competency register'), ('home.competency.find_team', 'Home competency find team'), ('home.competency.add_calendar', 'Home competency add calendar'), ('home.aspiration.filter_all', 'Home aspiration filter all'), ('home.aspiration.filter_public', 'Home aspiration filter public'), ('home.aspiration.filter_anonymous', 'Home aspiration filter anonymous'), ('home.aspiration.upvote', 'Home aspiration upvote'), ('home.aspiration.downvote', 'Home aspiration downvote'), ('home.ticket.track', 'Home ticket track'), ('home.ticket.view_form', 'Home ticket view form')], max_length=120, unique=True)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['action_key'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_key', models.CharField(choices=[('home.hero.access_academic', 'Home hero access academic'), ('home.hero.info_competition', 'Home hero info competition'), ('home.about.access_academic', 'Home about access academic'), ('home.about.info_competition', 'Home about info competition'), ('home.features.academic.access_now', 'Home features academic access now'), ('home.features.competency.explore', 'Home features competency explore'), ('home.features.career.view_resource', 'Home features career view resource'), ('home.features.advocacy.submit_aspiration', 'Home features advocacy submit aspiration'), ('home.competency.view_all', 'Home competency view all'), ('home.competency.register', 'Home competency register'), ('home.competency.find_team', 'Home competency find team'), ('home.competency.add_calendar', 'Home competency add calendar'), ('home.aspiration.filter_all', 'Home aspiration filter all'), ('home.aspiration.filter_public', 'Home aspiration filter public'), ('home.aspiration.filter_anonymous', 'Home aspiration filter anonymous'), ('home.aspiration.upvote', 'Home aspiration upvote'), ('home.aspiration.downvote', 'Home aspiration downvote'), ('home.ticket.track', 'Home ticket track'), ('home.ticket.view_form', 'Home ticket view form')], max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('page_path', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('target_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, max_length=120, null=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('user_hash', models.CharField(blank=True, max_length=64)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics_dashboard.activityeventcounter')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('action_key', 'idempotency_key'), name='unique_activity_event_idempotency_key')],
            },
        ),
    ]
