# Generated by Django 6.0.3 on 2026-03-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_cabinetcalendar_aboutsection_herosection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cabinetcalendar",
            name="display_order",
        ),
        migrations.AlterModelOptions(
            name="cabinetcalendar",
            options={"ordering": ["-updated_at", "title"]},
        ),
        migrations.AddConstraint(
            model_name="cabinetcalendar",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_cabinet_calendar",
            ),
        ),
    ]
