# Generated by Django 6.0.3 on 2026-05-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_update_cabinetcalendar_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='bincang_sekma_link',
            field=models.URLField(blank=True, verbose_name='Bincang Sekma'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='branding_dokumentasi_link',
            field=models.URLField(blank=True, verbose_name='Branding & Dokumentasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='business_partnership_link',
            field=models.URLField(blank=True, verbose_name='Business Partnership'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='career_catalyst_link',
            field=models.URLField(blank=True, verbose_name='Career Catalyst'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='explore_link',
            field=models.URLField(blank=True, verbose_name='EXPLORE'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='extensipedia_link',
            field=models.URLField(blank=True, verbose_name='Extensipedia'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='fun_enlightenment_link',
            field=models.URLField(blank=True, verbose_name='Fun Enlightenment'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='jaring_aspirasi_link',
            field=models.URLField(blank=True, verbose_name='Jaring Aspirasi'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='kajian_strategis_link',
            field=models.URLField(blank=True, verbose_name='Kajian Strategis'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='reach_project_link',
            field=models.URLField(blank=True, verbose_name='REACH Project'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='study_boost_exam_blast_link',
            field=models.URLField(blank=True, verbose_name='Study Boost & Exam Blast'),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='talent_interest_link',
            field=models.URLField(blank=True, verbose_name='Talent Interest'),
        ),
    ]
