# Generated by Django 6.0.3 on 2026-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_careerresourceconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerresourceconfiguration',
            name='portfolio_guide',
            field=models.URLField(verbose_name='Job interview prep'),
        ),
        migrations.AlterField(
            model_name='careerresourceconfiguration',
            name='salary_script',
            field=models.URLField(verbose_name='Compensation & benefit research'),
        ),
    ]
